
### default get rest
GET http://localhost:5000/

### adding drone to database
POST  http://localhost:5000/drone/add/
content-type: application/json

{
    "model": "1234567890", "serial_number": "0987654321",
    "weight_limit": "56", "battery_capacity": 85,
    "state": "IDLE"
}

### adding a medication load
POST  http://localhost:5000/medication/add/
content-type: application/json

{
    "name": "Lumerthem", "weight": 2500.05,
    "code": "0x1237450", "image": "URL"
}

### dispatching a drone
POST  http://localhost:5000/drone/load/
content-type: application/json

{
   "serial_number": "2341234", "load_id": "4"
}

### checking loaded drone items
POST  http://localhost:5000/drone/items/
content-type: application/json

{
   "state": "LOADED"
}

### checking drones by current state
POST  http://localhost:5000/drone/list/
content-type: application/json

{
   "state": "IDLE"
}


### get drone battery level
POST  http://localhost:5000/drone/battery/
content-type: application/json

{
   "serial_number": "12345678"
}